<html>
    <head>
        <title>Index</title>
    </head>
    
    <body>
        <div id="main">
            <div id="header">
                <h1>TianguisCabal</h1>
            </div>

            <div id="content">
                <p>Hola, amigos!</p>
                <p>
                   <strong>Value:</strong> <?php print_r($Vars); ?>
            </div>

            <div id="footer">
                <small>TianguisCabal <?php echo date('Y'); ?></small>
            </div>
        </div>
    </body>
</html>
